name: IAA
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - _r-mutex=1.0.1=anacondar_1
  - abseil-cpp=20210324.2=h9c3ff4c_0
  - alsa-lib=1.2.3=h516909a_0
  - anyio=3.3.4=py39hf3d152e_1
  - aplus=0.11.0=py_1
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argon2-cffi=21.1.0=py39h3811e60_2
  - arrow-cpp=5.0.0=py39h247a7eb_8_cpu
  - astropy=4.3.1=py39hce5d2b2_2
  - async_generator=1.10=py_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - aws-c-cal=0.5.11=h95a6274_0
  - aws-c-common=0.6.2=h7f98852_0
  - aws-c-event-stream=0.2.7=h3541f99_13
  - aws-c-io=0.10.5=hfb6a706_0
  - aws-checksums=0.1.11=ha31a3da_7
  - aws-sdk-cpp=1.8.186=hb4091e7_3
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - binutils_impl_linux-64=2.36.1=h193b22a_2
  - binutils_linux-64=2.36=hf3e587d_1
  - blake3=0.2.1=py39h860a657_0
  - bleach=4.1.0=pyhd8ed1ab_0
  - blosc=1.21.0=h9c3ff4c_0
  - bokeh=2.4.1=py39hf3d152e_1
  - bqplot=0.12.31=pyhd8ed1ab_0
  - branca=0.4.2=pyhd8ed1ab_0
  - brotli=1.0.9=h7f98852_5
  - brotli-bin=1.0.9=h7f98852_5
  - brotlipy=0.7.0=py39h3811e60_1003
  - brunsli=0.1=h9c3ff4c_0
  - bwidget=1.9.14=ha770c72_1
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - c-blosc2=2.0.4=h5f21a17_1
  - ca-certificates=2021.10.8=ha878542_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=4.2.4=pyhd8ed1ab_0
  - cairo=1.16.0=h6cf1ce9_1008
  - certifi=2021.10.8=py39hf3d152e_1
  - cffi=1.15.0=py39h4bc2ebd_0
  - cfitsio=4.0.0=h9a35b8e_0
  - chardet=4.0.0=py39hf3d152e_2
  - charls=2.2.0=h9c3ff4c_0
  - charset-normalizer=2.0.0=pyhd8ed1ab_0
  - click=8.0.3=py39hf3d152e_1
  - cloudpickle=2.0.0=pyhd8ed1ab_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - conda-package-handling=1.7.3=py39h3811e60_1
  - cryptography=35.0.0=py39h95dcef6_2
  - curl=7.80.0=h2574ce0_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cytoolz=0.11.2=py39h3811e60_1
  - dask=2021.7.1=pyhd8ed1ab_0
  - dask-core=2021.7.1=pyhd8ed1ab_0
  - dask-jobqueue=0.7.0=py_0
  - dbus=1.13.6=h48d8840_2
  - debugpy=1.5.1=py39he80948d_0
  - decorator=5.1.0=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - distributed=2021.7.1=py39hf3d152e_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.4.1=h9c3ff4c_0
  - fastapi=0.70.0=pyhd8ed1ab_0
  - filelock=3.3.2=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.1=hba837de_1005
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.10.4=h0708190_1
  - fribidi=1.0.10=h36c2ea0_0
  - frozendict=2.0.3=pyhd8ed1ab_0
  - fsspec=2021.11.0=pyhd8ed1ab_0
  - future=0.18.2=py39hf3d152e_4
  - gcc_impl_linux-64=9.4.0=h03d3576_11
  - gcc_linux-64=9.4.0=h391b98a_1
  - geos=3.10.0=h9c3ff4c_0
  - gettext=0.19.8.1=h73d1719_1008
  - gflags=2.2.2=he1b5a44_1004
  - gfortran_impl_linux-64=9.4.0=h0003116_11
  - gfortran_linux-64=9.4.0=hf0ab688_1
  - giflib=5.2.1=h36c2ea0_2
  - glib=2.70.0=h780b84a_1
  - glib-tools=2.70.0=h780b84a_1
  - glog=0.5.0=h48cff8f_0
  - graphite2=1.3.13=h58526e2_1001
  - grpc-cpp=1.40.0=h05f19cf_2
  - gsl=2.7=he838d99_0
  - gst-plugins-base=1.18.5=hf529b03_2
  - gstreamer=1.18.5=h9f60fe5_2
  - gxx_impl_linux-64=9.4.0=h03d3576_11
  - gxx_linux-64=9.4.0=h0316aca_1
  - h5py=3.3.0=nompi_py39h98ba4bc_100
  - harfbuzz=3.1.1=h83ec7ef_0
  - hdf5=1.10.6=nompi_h6a2412b_1114
  - heapdict=1.0.1=py_0
  - icu=68.2=h9c3ff4c_0
  - idna=3.1=pyhd3deb0d_0
  - imagecodecs=2021.8.26=py39h571908b_2
  - imageio=2.9.0=py_0
  - importlib-metadata=4.8.2=py39hf3d152e_0
  - importlib_metadata=4.8.2=hd8ed1ab_0
  - importlib_resources=5.4.0=pyhd8ed1ab_0
  - ipydatawidgets=4.2.0=pyhd3deb0d_0
  - ipykernel=6.5.0=py39hef51801_0
  - ipyleaflet=0.14.0=pyhd8ed1ab_1
  - ipympl=0.8.2=pyhd8ed1ab_0
  - ipython=7.29.0=py39hef51801_1
  - ipython_genutils=0.2.0=py_1
  - ipyvolume=0.6.0a8=pyhd8ed1ab_0
  - ipyvue=1.7.0=pyhd8ed1ab_0
  - ipyvuetify=1.8.1=pyhd8ed1ab_0
  - ipywebrtc=0.6.0=pyhd8ed1ab_0
  - ipywidgets=7.6.5=pyhd8ed1ab_0
  - jbig=2.1=h7f98852_2003
  - jedi=0.18.0=py39hf3d152e_3
  - jinja2=3.0.3=pyhd8ed1ab_0
  - jpeg=9d=h36c2ea0_0
  - jsonschema=4.2.1=pyhd8ed1ab_0
  - jupyter_client=7.0.6=pyhd8ed1ab_0
  - jupyter_core=4.9.1=py39hf3d152e_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_widgets=1.0.2=pyhd8ed1ab_0
  - jxrlib=1.1=h7f98852_2
  - kernel-headers_linux-64=2.6.32=he073ed8_15
  - kiwisolver=1.3.2=py39h1a9c180_1
  - krb5=1.19.2=hcc1bbae_3
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libaec=1.0.6=h9c3ff4c_0
  - libarchive=3.5.2=hccf745f_1
  - libblas=3.9.0=12_linux64_openblas
  - libbrotlicommon=1.0.9=h7f98852_5
  - libbrotlidec=1.0.9=h7f98852_5
  - libbrotlienc=1.0.9=h7f98852_5
  - libcblas=3.9.0=12_linux64_openblas
  - libclang=11.1.0=default_ha53f305_1
  - libcurl=7.80.0=h2574ce0_0
  - libdeflate=1.8=h7f98852_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h7f98852_5
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-devel_linux-64=9.4.0=hd854feb_11
  - libgcc-ng=11.2.0=h1d223b6_11
  - libgfortran-ng=11.2.0=h69a702a_11
  - libgfortran5=11.2.0=h5c6108e_11
  - libglib=2.70.0=h174f98d_1
  - libgomp=11.2.0=h1d223b6_11
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=12_linux64_openblas
  - libllvm10=10.0.1=he513fc3_3
  - libllvm11=11.1.0=hf817b99_2
  - libmamba=0.18.1=h3985d26_1
  - libmambapy=0.18.1=py39h8bfa403_1
  - libnghttp2=1.43.0=h812cca2_1
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.18=pthreads_h8fe5266_0
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=h21135ba_2
  - libpq=13.3=hd57d9b9_3
  - libprotobuf=3.18.1=h780b84a_0
  - libsanitizer=9.4.0=h79bfe98_11
  - libsodium=1.0.18=h36c2ea0_1
  - libsolv=0.7.19=h780b84a_5
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-devel_linux-64=9.4.0=hd854feb_11
  - libstdcxx-ng=11.2.0=he4da1e4_11
  - libthrift=0.15.0=he6d91bd_1
  - libtiff=4.3.0=h6f004c6_2
  - libutf8proc=2.6.1=h7f98852_0
  - libuuid=2.32.1=h7f98852_1000
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.2.1=h7f98852_0
  - libxcb=1.13=h7f98852_1003
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h72842e0_0
  - libzlib=1.2.11=h36c2ea0_1013
  - libzopfli=1.0.3=h9c3ff4c_0
  - llvmlite=0.36.0=py39h1bbdace_0
  - locket=0.2.0=py_2
  - lz4-c=1.9.3=h9c3ff4c_1
  - lzo=2.10=h516909a_1000
  - make=4.3=hd18ef5c_1
  - markupsafe=2.0.1=py39h3811e60_1
  - matplotlib=3.4.2=py39hf3d152e_0
  - matplotlib-base=3.4.2=py39h2fa2bec_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mistune=0.8.4=py39h3811e60_1005
  - mock=4.0.3=py39hf3d152e_2
  - mono=6.12.0.90=h780b84a_0
  - msgpack-python=1.0.2=py39h1a9c180_2
  - mysql-common=8.0.27=ha770c72_1
  - mysql-libs=8.0.27=hfa10184_1
  - nbclient=0.5.5=pyhd8ed1ab_0
  - nbconvert=6.2.0=py39hf3d152e_0
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=h58526e2_4
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - networkx=2.6.3=pyhd8ed1ab_1
  - notebook=6.4.5=pyha770c72_0
  - nspr=4.32=h9c3ff4c_1
  - nss=3.71=hb5efdd6_0
  - numba=0.53.1=py39h56b8d98_1
  - numexpr=2.7.3=py39hde0f152_1
  - numpy=1.21.1=py39hdbf815f_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1l=h7f98852_0
  - orc=1.7.0=h68e2c4e_0
  - packaging=21.0=pyhd8ed1ab_0
  - pandas=1.3.1=py39hde0f152_0
  - pandoc=2.16=h7f98852_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.48.10=h54213e6_2
  - parquet-cpp=1.5.1=2
  - parso=0.8.2=pyhd8ed1ab_0
  - partd=1.2.0=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.37=h032f7d1_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.3.1=py39ha612740_0
  - pip=21.3.1=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pooch=1.5.2=pyhd8ed1ab_0
  - progressbar2=3.53.1=pyh9f0ad1d_0
  - prometheus_client=0.12.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.22=pyha770c72_0
  - psutil=5.8.0=py39h3811e60_2
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pyarrow=5.0.0=py39h3ebc44c_8_cpu
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.3=py39h3811e60_1009
  - pycparser=2.21=pyhd8ed1ab_0
  - pydantic=1.8.2=py39h3811e60_2
  - pyerfa=2.0.0.1=py39hce5d2b2_1
  - pygments=2.10.0=pyhd8ed1ab_0
  - pyopenssl=21.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.5=pyhd8ed1ab_0
  - pyqt=5.12.3=py39hf3d152e_7
  - pyqt-impl=5.12.3=py39h0fcd23e_7
  - pyqt5-sip=4.19.18=py39he80948d_7
  - pyqtchart=5.12=py39h0fcd23e_7
  - pyqtwebengine=5.12.1=py39h0fcd23e_7
  - pyrsistent=0.18.0=py39h3811e60_0
  - pysocks=1.7.1=py39hf3d152e_4
  - pytables=3.6.1=py39hf6dc253_3
  - python=3.9.7=hb7a2778_3_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-utils=2.5.6=pyh44b312d_0
  - python_abi=3.9=2_cp39
  - pythreejs=2.3.0=pyhd8ed1ab_0
  - pytz=2021.3=pyhd8ed1ab_0
  - pywavelets=1.2.0=py39hce5d2b2_0
  - pyyaml=6.0=py39h3811e60_3
  - pyzmq=22.3.0=py39h37b5a0c_1
  - qt=5.12.9=hda022c4_4
  - r-base=4.1.1=hb93adac_1
  - r-cli=3.1.0=r41h03ef668_0
  - r-crayon=1.4.2=r41hc72bb7e_0
  - r-data.table=1.14.2=r41hcfec24a_0
  - r-dplyr=1.0.7=r41h03ef668_0
  - r-ellipsis=0.3.2=r41hcfec24a_0
  - r-fansi=0.4.2=r41hcfec24a_0
  - r-generics=0.1.1=r41hc72bb7e_0
  - r-glue=1.5.0=r41hcfec24a_0
  - r-lifecycle=1.0.1=r41hc72bb7e_0
  - r-magrittr=2.0.1=r41hcfec24a_1
  - r-pillar=1.6.4=r41hc72bb7e_0
  - r-pkgconfig=2.0.3=r41hc72bb7e_1
  - r-purrr=0.3.4=r41hcfec24a_1
  - r-r6=2.5.1=r41hc72bb7e_0
  - r-rlang=0.4.12=r41hcfec24a_0
  - r-stringi=1.7.5=r41hcabe038_0
  - r-stringr=1.4.0=r41hc72bb7e_2
  - r-tibble=3.1.6=r41hcfec24a_0
  - r-tidyselect=1.1.1=r41hc72bb7e_0
  - r-utf8=1.2.2=r41hcfec24a_0
  - r-vctrs=0.3.8=r41hcfec24a_1
  - re2=2021.09.01=h9c3ff4c_0
  - readline=8.1=h46c0cb4_0
  - reproc=14.2.3=h7f98852_0
  - reproc-cpp=14.2.3=h9c3ff4c_0
  - requests=2.26.0=pyhd8ed1ab_0
  - ruamel_yaml=0.15.80=py39h3811e60_1006
  - s2n=1.0.10=h9b69904_0
  - scikit-image=0.18.2=py39hde0f152_0
  - scipy=1.7.0=py39hee8e79c_1
  - sed=4.8=he412f7d_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=58.5.3=py39hf3d152e_0
  - shapely=1.8.0=py39hc7dd4e9_2
  - six=1.16.0=pyh6c4a22f_0
  - snakeviz=2.1.0=pyh9f0ad1d_0
  - snappy=1.1.8=he1b5a44_3
  - sniffio=1.2.0=py39hf3d152e_2
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - sqlite=3.36.0=h9cd32fc_2
  - starlette=0.16.0=pyhd8ed1ab_0
  - sysroot_linux-64=2.12=he073ed8_15
  - tabulate=0.8.9=pyhd8ed1ab_0
  - tblib=1.7.0=pyhd8ed1ab_0
  - terminado=0.12.1=py39hf3d152e_1
  - testpath=0.5.0=pyhd8ed1ab_0
  - tifffile=2021.11.2=pyhd8ed1ab_0
  - tk=8.6.11=h27826a3_1
  - tktable=2.10=hb7b940f_3
  - toolz=0.11.1=py_0
  - tornado=6.1=py39h3811e60_2
  - tqdm=4.62.3=pyhd8ed1ab_0
  - traitlets=5.1.1=pyhd8ed1ab_0
  - traittypes=0.2.1=pyh9f0ad1d_2
  - typing-extensions=3.10.0.2=hd8ed1ab_0
  - typing_extensions=3.10.0.2=pyha770c72_0
  - tzdata=2021e=he74cb21_0
  - urllib3=1.26.7=pyhd8ed1ab_0
  - vaex=4.5.0=pyhd8ed1ab_0
  - vaex-astro=0.8.3=pyhd8ed1ab_0
  - vaex-core=4.5.1=py39h50574b8_0
  - vaex-hdf5=0.10.0=pyhd8ed1ab_0
  - vaex-jupyter=0.6.0=pyhd8ed1ab_0
  - vaex-ml=0.14.0=pyhd8ed1ab_0
  - vaex-server=0.6.1=pyhd8ed1ab_0
  - vaex-viz=0.5.0=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.37.0=pyhd8ed1ab_1
  - widgetsnbextension=3.5.2=py39hf3d152e_0
  - xarray=0.20.1=pyhd8ed1ab_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-libxt=1.2.1=h7f98852_2
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - yaml-cpp=0.6.3=he1b5a44_4
  - zeromq=4.3.4=h9c3ff4c_1
  - zfp=0.5.5=h9c3ff4c_7
  - zict=2.0.0=py_0
  - zipp=3.6.0=pyhd8ed1ab_0
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.5.0=ha95c52a_0
prefix: /home/lconnelly/miniconda3/envs/IAA
